openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/search/:
    get:
      operationId: listTips
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
  /api/edit/{id}/:
    get:
      operationId: retrieveTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
    put:
      operationId: updateTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tips'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tips'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tips'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tips'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tips'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tips'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/tips/:
    get:
      operationId: listTips
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
    post:
      operationId: createTips
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tips'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tips'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tips'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
  /api/tips/{id}/:
    get:
      operationId: retrieveTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
    put:
      operationId: updateTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tips'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tips'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tips'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tips'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tips'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tips'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyTips
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tips.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/tags/:
    get:
      operationId: listTags
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tags'
          description: ''
      tags:
      - api
    post:
      operationId: createTags
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tags'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tags'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tags'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
          description: ''
      tags:
      - api
  /api/tags/{id}/:
    get:
      operationId: retrieveTags
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tags.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
          description: ''
      tags:
      - api
    put:
      operationId: updateTags
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tags.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tags'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tags'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tags'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateTags
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tags.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tags'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tags'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tags'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyTags
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this tags.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /users/create_user/:
    post:
      operationId: createUser
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - users
  /api/create_tip/:
    post:
      operationId: createTips
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tips'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tips'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tips'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tips'
          description: ''
      tags:
      - api
components:
  schemas:
    Tips:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          readOnly: true
        tip:
          type: string
          maxLength: 400
        account:
          type: string
          maxLength: 200
        email:
          type: string
          format: email
          maxLength: 254
        links_set:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              name:
                type: string
                maxLength: 256
              tip:
                type: integer
            required:
            - name
          readOnly: true
        tags:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              name:
                type: string
                maxLength: 256
            required:
            - name
          readOnly: true
        retweets:
          type: integer
          readOnly: true
        likes:
          type: integer
          readOnly: true
      required:
      - tip
    Tags:
      type: object
      properties:
        name:
          type: string
          maxLength: 256
        tips_set:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              timestamp:
                type: string
                format: date-time
                readOnly: true
              tip:
                type: string
                maxLength: 400
              email:
                type: string
                format: email
                maxLength: 254
              account:
                type: string
                maxLength: 200
              likes:
                type: integer
                nullable: true
              retweets:
                type: integer
                nullable: true
              tags:
                type: array
                items:
                  type: integer
            required:
            - tip
          readOnly: true
      required:
      - name
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          maxLength: 100
      required:
      - username
      - password
